# Generated by Django 5.2.4 on 2025-07-05 12:50

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(help_text='Введите название мебели', max_length=50, verbose_name='Категории мебели')),
                ('slug', models.SlugField(unique=True)),
                ('main_image', models.ImageField(blank=True, help_text='Загрузите изображение категории', null=True, upload_to='categories/%Y/%m/%d/', verbose_name='Изображение')),
                ('order', models.PositiveIntegerField(default=0, help_text='Чем выше число, тем выше в списке', verbose_name='Порядок сортировки')),
                ('meta_title', models.CharField(blank=True, help_text='Для SEO (макс. 80 символов)', max_length=80, verbose_name='Мета-заголовок')),
                ('meta_description', models.CharField(blank=True, help_text='Для SEO (макс. 160 символов)', max_length=160, verbose_name='Мета-описание')),
                ('is_active', models.BooleanField(default=True, help_text='Отображать категорию на сайте', verbose_name='Активна')),
                ('parent', models.ForeignKey(blank=True, help_text='Для создания подкатегорий', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='children', to='mebel.category', verbose_name='Родительская категория')),
            ],
            options={
                'verbose_name': 'Категория',
                'verbose_name_plural': 'Категории',
                'db_table': 'categories',
                'ordering': ['-order', 'name'],
            },
        ),
        migrations.CreateModel(
            name='Image',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('src', models.ImageField(help_text='Загрузите дополнительное фото категории', upload_to='categories/images/%Y/%m/%d/', verbose_name='Изображение')),
                ('alt', models.CharField(blank=True, help_text='Описание изображения для SEO и доступности', max_length=255, validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['jpg', 'jpeg', 'png', 'webp', 'avif', 'gif'], message='Разрешены только изображения в форматах: JPG, PNG, WEBP, AVIF')], verbose_name='Альтернативный текст')),
                ('order', models.PositiveIntegerField(default=0, help_text='Порядок отображения изображений (меньше = раньше)', verbose_name='Порядок сортировки')),
                ('category', models.ForeignKey(help_text='Выберите категорию для изображения', on_delete=django.db.models.deletion.CASCADE, related_name='additional_images', to='mebel.category', verbose_name='Категория')),
            ],
            options={
                'verbose_name': 'Изображение категории',
                'verbose_name_plural': 'Изображения категорий',
                'db_table': 'category_images',
                'ordering': ['order', 'created'],
            },
        ),
    ]
