# Generated by Django 5.2.4 on 2025-07-05 13:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mebel', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='image',
            name='src',
            field=models.ImageField(help_text='Загрузите дополнительное фото категории', upload_to='categories/images/', verbose_name='Изображение'),
        ),
    ]
