# Generated by Django 5.2.4 on 2025-07-11 14:25

import mebel.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mebel', '0003_category_meta_keywords_alter_category_main_image'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='image',
            name='alt',
        ),
        migrations.AlterField(
            model_name='category',
            name='main_image',
            field=models.ImageField(blank=True, null=True, upload_to=mebel.models.path_to_image, verbose_name='Оригинальное изображение'),
        ),
        migrations.AlterField(
            model_name='image',
            name='src',
            field=models.ImageField(upload_to='categories/images/', verbose_name='Оригинальное изображение'),
        ),
    ]
