# Generated by Django 5.2.4 on 2025-07-11 14:53

import django.core.validators
import django.db.models.deletion
import mebel.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mebel', '0004_remove_image_alt_alter_category_main_image_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='alt',
            field=models.CharField(blank=True, help_text='Описание изображения для доступности и SEO', max_length=255, verbose_name='Альтернативный текст'),
        ),
        migrations.AddField(
            model_name='image',
            name='alt',
            field=models.CharField(blank=True, help_text='Описание изображения для доступности и SEO', max_length=255, verbose_name='Альтернативный текст'),
        ),
        migrations.AlterField(
            model_name='category',
            name='created',
            field=models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='Дата создания'),
        ),
        migrations.AlterField(
            model_name='category',
            name='is_active',
            field=models.BooleanField(db_index=True, default=True, help_text='Отображать категорию на сайте', verbose_name='Активна'),
        ),
        migrations.AlterField(
            model_name='category',
            name='main_image',
            field=models.ImageField(blank=True, help_text='Загрузите основное изображение категории', null=True, upload_to=mebel.models.path_to_image, validators=[mebel.models.validate_image_extension], verbose_name='Основное изображение'),
        ),
        migrations.AlterField(
            model_name='category',
            name='meta_description',
            field=models.CharField(blank=True, help_text='Описание для SEO (макс. 160 символов)', max_length=160, verbose_name='SEO описание'),
        ),
        migrations.AlterField(
            model_name='category',
            name='meta_keywords',
            field=models.CharField(blank=True, help_text='Ключевые слова через запятую (макс. 255 символов)', max_length=255, null=True, verbose_name='SEO ключевые слова'),
        ),
        migrations.AlterField(
            model_name='category',
            name='meta_title',
            field=models.CharField(blank=True, help_text='Заголовок для SEO (макс. 80 символов)', max_length=80, verbose_name='SEO заголовок'),
        ),
        migrations.AlterField(
            model_name='category',
            name='name',
            field=models.CharField(help_text='Введите название категории мебели', max_length=50, validators=[django.core.validators.MinLengthValidator(2)], verbose_name='Название категории'),
        ),
        migrations.AlterField(
            model_name='category',
            name='order',
            field=models.PositiveIntegerField(db_index=True, default=0, help_text='Чем выше число, тем выше в списке', verbose_name='Порядок сортировки'),
        ),
        migrations.AlterField(
            model_name='category',
            name='parent',
            field=models.ForeignKey(blank=True, help_text='Для создания иерархии категорий', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='children', to='mebel.category', verbose_name='Родительская категория'),
        ),
        migrations.AlterField(
            model_name='category',
            name='slug',
            field=models.SlugField(help_text='Уникальная часть URL для категории', max_length=60, unique=True, verbose_name='URL-идентификатор'),
        ),
        migrations.AlterField(
            model_name='category',
            name='updated',
            field=models.DateTimeField(auto_now=True, db_index=True, verbose_name='Дата обновления'),
        ),
        migrations.AlterField(
            model_name='image',
            name='created',
            field=models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='Дата создания'),
        ),
        migrations.AlterField(
            model_name='image',
            name='order',
            field=models.PositiveIntegerField(db_index=True, default=0, help_text='Порядок отображения (меньше = раньше)', verbose_name='Порядок сортировки'),
        ),
        migrations.AlterField(
            model_name='image',
            name='src',
            field=models.ImageField(help_text='Загрузите дополнительное изображение', upload_to=mebel.models.additional_image_path, validators=[mebel.models.validate_image_extension], verbose_name='Изображение'),
        ),
        migrations.AlterField(
            model_name='image',
            name='updated',
            field=models.DateTimeField(auto_now=True, db_index=True, verbose_name='Дата обновления'),
        ),
        migrations.AddIndex(
            model_name='category',
            index=models.Index(fields=['name', 'is_active'], name='categories_name_7b882a_idx'),
        ),
        migrations.AddIndex(
            model_name='image',
            index=models.Index(fields=['category', 'order'], name='category_im_categor_b73c6f_idx'),
        ),
    ]
