# Generated by Django 5.2.4 on 2025-07-12 20:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mebel', '0005_category_alt_image_alt_alter_category_created_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='description',
            field=models.TextField(blank=True, help_text='Детальное описание категории (можно использовать HTML)', verbose_name='Описание категории'),
        ),
    ]
